version: 2.1

jobs:
  build:
    docker:
#      - image: node:lts-slim
      - image: node:lts-bullseye

    steps:
      - checkout
      - run: npm install
      - run: npm run build

  deploy:
    docker:
      - image: node:lts-bullseye
    steps:
      - checkout
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "circleci@example.com"
            git config --global user.name "CircleCI"
            git checkout gh-pages
            git rm -rf .
            cp -r dist/* .
            rm dist -r
            git commit --allow-empty -m "Clean gh-pages branch"
            git push -f origin gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
#          filters:
#            branches:
#              only:
#                - main
