version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:20

    steps:
      - checkout
      - run: npm install
      - run: npm run build

  deploy:
    docker:
      - image: circleci/node:20

    steps:
      - checkout
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "circleci@example.com"
            git config --global user.name "CircleCI"
            git checkout gh-pages
            git rm -rf .
            cp -r dist/* .
            git commit -m "Clean gh-pages branch"
            git push origin gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
#                - main
                 - \#1-travis-ci-setup
